# Machine Learning Foundation

## Section 2, Part e: Regularization LAB


## Lib Imports

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.set_printoptions(precision=3, suppress=True)
np.random.seed(72081)

## Import Local Libs

In [5]:
import sys, os

In [6]:
sys.path.append('../')

In [9]:
from lib.helpers import download

## Helper Methods

In [49]:
def to_2d(array: np.array) -> np.array:
    return array.reshape(array.shape[0], -1)

def plot_exponential_data() -> np.array:
    data = np.exp(np.random.normal(size=1000))
    plt.hist(data)
    plt.show()
    return data

def plot_square_normal_data():
    data = np.square(np.random.normal(loc=5, size=1000))
    plt.hist(data)
    plt.show()
    return data

def X_and_y_from_df(df: pd.DataFrame,
                    y_col: str) -> tuple[np.array, np.array]:
    X = boston_data.drop(Y_COL, axis=1)
    y = boston_data[Y_COL]
    return(X, y)
    

## Load Boston Data

In [13]:
from sklearn.datasets import fetch_openml

boston =  fetch_openml(data_id=506)
path = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML240EN-SkillsNetwork/labs/data/boston_housing_clean.pickle"
download(path, 'boston_housing_clean.pickle')

content <Response [200]>


In [14]:
with open('boston_housing_clean.pickle', 'rb') as to_read:
    boston = pd.read_pickle(to_read)
    
boston_data = boston['dataframe']
boston_description = boston['description']
boston_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

# Globals

In [47]:
Y_COL = 'MEDV'

## Data Standardization

**Standardizing** data refers to transforming each variable so that it more closely follows a **standard** normal distribution, with mean 0 and standard deviation 1.

The [`StandardScaler`](http://scikit-learn.org/dev/modules/generated/sklearn.preprocessing.StandardScaler.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML240ENSkillsNetwork34171862-2022-01-01#sklearn.preprocessing.StandardScaler) object in SciKit Learn can do this.


In [51]:
X, y = X_and_y_from_df(boston_data, Y_COL)

In [19]:
from sklearn.preprocessing import StandardScaler

s = StandardScaler()
X_ss = s.fit_transform(X)
X_ss

array([[-0.418,  0.285, -1.288, ..., -1.459,  0.441, -1.076],
       [-0.415, -0.488, -0.593, ..., -0.303,  0.441, -0.492],
       [-0.415, -0.488, -0.593, ..., -0.303,  0.396, -1.209],
       ...,
       [-0.411, -0.488,  0.116, ...,  1.176,  0.441, -0.983],
       [-0.406, -0.488,  0.116, ...,  1.176,  0.403, -0.865],
       [-0.413, -0.488,  0.116, ...,  1.176,  0.441, -0.669]])

### Exercise:

Confirm standard scaling


In [34]:
a = np.array([[1, 2, 12],
              [8, 12, 2],
              [5, 32, 7]])

In [35]:
column_mean = a.mean(axis=0)
column_mean

array([ 4.667, 15.333,  7.   ])

In [36]:
a_diff = a - a.mean(axis=0)
a_diff

array([[ -3.667, -13.333,   5.   ],
       [  3.333,  -3.333,  -5.   ],
       [  0.333,  16.667,   0.   ]])

In [39]:
a_std = a.std(axis=0)
a_std

array([ 2.867, 12.472,  4.082])

In [37]:
row_mean = a.mean(axis=1)
row_mean

array([ 5.   ,  7.333, 14.667])

In [38]:
a_ss = s.fit_transform(a)
a_ss

array([[-1.279, -1.069,  1.225],
       [ 1.162, -0.267, -1.225],
       [ 0.116,  1.336,  0.   ]])

In [41]:
X2 = np.array(X)
X2_ss = (X2 - X2.mean(axis=0)) / X2.std(axis=0)
X2_ss

array([[-0.418,  0.285, -1.288, ..., -1.459,  0.441, -1.076],
       [-0.415, -0.488, -0.593, ..., -0.303,  0.441, -0.492],
       [-0.415, -0.488, -0.593, ..., -0.303,  0.396, -1.209],
       ...,
       [-0.411, -0.488,  0.116, ...,  1.176,  0.441, -0.983],
       [-0.406, -0.488,  0.116, ...,  1.176,  0.403, -0.865],
       [-0.413, -0.488,  0.116, ...,  1.176,  0.441, -0.669]])

In [42]:
np.allclose(X2_ss, X_ss)

True

## Coefficients with and without Scaling

In [46]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

In [52]:
X, y = X_and_y_from_df(boston_data, Y_COL)

In [53]:
lr = LinearRegression()

In [54]:
lr.fit(X, y)

LinearRegression()

In [56]:
lr.coef_

array([ -0.107,   0.046,   0.021,   2.689, -17.796,   3.805,   0.001,
        -1.476,   0.306,  -0.012,  -0.953,   0.009,  -0.525])

In [57]:
pipeline = Pipeline(
    steps=[
        ('ss', StandardScaler()),
        ('lr', LinearRegression())
    ]
)

In [61]:
pipeline.fit(X, y)

Pipeline(steps=[('ss', StandardScaler()), ('lr', LinearRegression())])

In [62]:
lr_updated = pipeline['lr']

In [63]:
lr_updated.coef_

array([-0.92 ,  1.081,  0.143,  0.682, -2.06 ,  2.671,  0.021, -3.104,
        2.659, -2.076, -2.062,  0.857, -3.749])

### Exercise:

Based on these results, what is the most "impactful" feature (this is intended to be slightly ambiguous)? "In what direction" does it affect "y"?

**Hint:** Recall from last week that we can "zip up" the names of the features of a DataFrame `df` with a model `model` fitted on that DataFrame using:

```python
dict(zip(df.columns.values, model.coef_))
```


In [66]:
feature_importances = pd.DataFrame(zip(X.columns, lr_updated.coef_))

In [67]:
feature_importances.sort_values(by=1)

0         1
12    LSTAT -3.748680
7       DIS -3.104448
9       TAX -2.075898
10  PTRATIO -2.062156
4       NOX -2.060092
0      CRIM -0.920411
6       AGE  0.021121
2     INDUS  0.142967
3      CHAS  0.682203
11        B  0.856640
1        ZN  1.080981
8       RAD  2.658787
5        RM  2.670641

## Lasso with and without scaling


We discussed Lasso in lecture.

Let's review together:

1.  What is different about Lasso vs. regular Linear Regression?
2.  Is standardization more or less important with Lasso vs. Linear Regression? Why?


In [69]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import PolynomialFeatures

In [85]:
lasso_pipeline = Pipeline([
        ('pf', PolynomialFeatures(degree=2, include_bias=False)),
        ('ss', StandardScaler()),
        ('lasso', Lasso())
    ]
)

In [86]:
lasso_pipeline.fit(X, y)

Pipeline(steps=[('pf', PolynomialFeatures(include_bias=False)),
                ('ss', StandardScaler()), ('lasso', Lasso())])

In [87]:
lasso_pipeline[-1].coef_

array([-0.   ,  0.   , -0.   ,  0.   , -0.   ,  0.   , -0.   , -0.   ,
       -0.   , -0.   , -0.991,  0.   , -0.   , -0.   ,  0.   , -0.   ,
        0.068, -0.   , -0.   , -0.   , -0.   , -0.   , -0.   , -0.   ,
       -0.   , -0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.   ,  0.   ,
       -0.   , -0.   , -0.   , -0.05 , -0.   , -0.   , -0.   , -0.   ,
       -0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   , -0.   , -0.   , -0.   , -0.   , -0.   ,
       -0.   , -0.   ,  0.   , -0.   ,  3.3  , -0.   , -0.   , -0.   ,
       -0.   , -0.   ,  0.42 , -3.498, -0.   , -0.   , -0.   , -0.   ,
       -0.   ,  0.   , -0.   , -0.   , -0.   , -0.146, -0.   , -0.   ,
       -0.   , -0.   , -0.   , -0.   , -0.   , -0.   , -0.   , -0.   ,
       -0.   , -0.   , -0.   ,  0.   , -0.   ,  0.   , -0.   , -0.   ])

### Exercise

Compare

*   Sum of magnitudes of the coefficients
*   Number of coefficients that are zero

for Lasso with alpha 0.1 vs. 1.

Before doing the exercise, answer the following questions in one sentence each:

*   Which do you expect to have greater magnitude?
*   Which do you expect to have more zeros?


In [99]:
def print_regression_coefficients(pipline: Pipeline):
    """_summary_

    Args:
        pipline (Pipeline): _description_
    """
    print(f"abs: {abs(pipline[-1].coef_).sum()}")
    print(f"num_zero: {(pipline[-1].coef_ != 0).sum()}")

In [92]:
lasso_pipeline.set_params(lasso__alpha=0.1)
lasso_pipeline.fit(X, y)

Pipeline(steps=[('pf', PolynomialFeatures(include_bias=False)),
                ('ss', StandardScaler()), ('lasso', Lasso(alpha=0.1))])

In [100]:
print_regression_coefficients(lasso_pipeline)

abs: 26.17241511542676
num_zero: 23


In [101]:
lasso_pipeline.set_params(lasso__alpha=1.0)
lasso_pipeline.fit(X, y)

Pipeline(steps=[('pf', PolynomialFeatures(include_bias=False)),
                ('ss', StandardScaler()), ('lasso', Lasso())])

In [102]:
print_regression_coefficients(lasso_pipeline)

abs: 8.472405227760158
num_zero: 7


With more regularization (higher alpha) we will expect the penalty for higher weights to be greater and thus the coefficients to be pushed down. Thus a higher alpha means lower magnitude with more coefficients pushed down to 0.


### Exercise: $R^2$


Calculate the $R^2$ of each model without train/test split.

Recall that we import $R^2$ using:

```python
from sklearn.metrics import r2_score
```


In [103]:
from sklearn.metrics import r2_score

y_pred = lasso_pipeline.predict(X)
r2_score(y, y_pred)

0.7207000461229028

### With train/test split

In [105]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3,
                                                    random_state=72018)

In [107]:
lasso_pipeline.set_params(lasso__alpha=1)
lasso_pipeline.fit(X_train, y_train)

Pipeline(steps=[('pf', PolynomialFeatures(include_bias=False)),
                ('ss', StandardScaler()), ('lasso', Lasso(alpha=1))])

In [108]:
y_pred = lasso_pipeline.predict(X_test)
r2_score(y_test, y_pred)

0.6780325981174931

In [109]:
lasso_pipeline.set_params(lasso__alpha=0.1)
lasso_pipeline.fit(X_train, y_train)

Pipeline(steps=[('pf', PolynomialFeatures(include_bias=False)),
                ('ss', StandardScaler()), ('lasso', Lasso(alpha=0.1))])

In [110]:
y_pred = lasso_pipeline.predict(X_test)
r2_score(y_test, y_pred)

0.799926134284606

### Exercise

#### Part 1:

Do the same thing with Lasso of:

*   `alpha` of 0.001
*   Increase `max_iter` to 100000 to ensure convergence.

Calculate the $R^2$ of the model.

Feel free to copy-paste code from above, but write a one sentence comment above each line of code explaining why you're doing what you're doing.

#### Part 2:

Do the same procedure as before, but with Linear Regression.

Calculate the $R^2$ of this model.

#### Part 3:

Compare the sums of the absolute values of the coefficients for both models, as well as the number of coefficients that are zero. Based on these measures, which model is a "simpler" description of the relationship between the features and the target?


In [111]:
lasso_pipeline.set_params(lasso__alpha=0.001, lasso__max_iter=100000)
lasso_pipeline.fit(X_train, y_train)
y_pred = lasso_pipeline.predict(X_test)
r2_score(y_test, y_pred)

0.8847893236874363

In [113]:
print_regression_coefficients(lasso_pipeline)

abs: 435.572322904404
num_zero: 90


In [112]:
lr_pipeline = Pipeline(
    steps=[
        ('pf', PolynomialFeatures(degree=2, include_bias=False)),
        ('ss', StandardScaler()),
        ('lr', LinearRegression())
    ]
)
lr_pipeline.fit(X_train, y_train)
y_pred = lr_pipeline.predict(X_test)
r2_score(y_test, y_pred)

0.8689110469231034

In [114]:
print_regression_coefficients(lr_pipeline)

abs: 1183.891813864903
num_zero: 104


## L1 vs. L2 Regularization


As mentioned in the deck: `Lasso` and `Ridge` regression have the same syntax in SciKit Learn.

Now we're going to compare the results from Ridge vs. Lasso regression:


### Exercise

Following the Ridge documentation from above:

1.  Define a Ridge object `r` with the same `alpha` as `las001`.
2.  Fit that object on `X` and `y` and print out the resulting coefficients.


In [117]:
from sklearn.linear_model import Ridge

rg_pipeline = Pipeline(
    steps=[
        ('pf', PolynomialFeatures(degree=2, include_bias=False)),
        ('ss', StandardScaler()),
        ('ridge', Ridge())
    ]
)

In [119]:
rg_pipeline.set_params(ridge__alpha=0.001)
rg_pipeline.fit(X_train, y_train)
y_pred = rg_pipeline.predict(X_test)
r2_score(y_test, y_pred)

0.870299626654349

In [ ]:
print_regression_coefficients(rg_pipeline)