# Softmax vs Log Softmax Activation

In [1]:
import tensorflow as tf
import numpy as np

2024-06-10 21:18:25.378956: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-10 21:18:25.568126: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-10 21:18:26.298669: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-10 21:18:28.168912: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
test_input = np.random.randn(2, 5)
test_input

array([[ 1.63729284, -0.09749303,  0.97332702,  0.20336661,  0.57404504],
       [-0.37534986, -0.68644202,  2.35098778,  1.75082809,  0.31497625]])

In [5]:
softmax_output = tf.nn.softmax(test_input)
softmax_output

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[0.43957064, 0.07755695, 0.22629345, 0.10478097, 0.15179799],
       [0.03651419, 0.02675199, 0.55782126, 0.30608991, 0.07282265]])>

In [7]:
log_softmax_output = tf.nn.log_softmax(test_input)
log_softmax_output

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[-0.82195686, -2.55674273, -1.48592268, -2.25588308, -1.88520466],
       [-3.31005434, -3.62114649, -0.58371669, -1.18387638, -2.61972823]])>

In [9]:
np.exp(log_softmax_output)

array([[0.43957064, 0.07755695, 0.22629345, 0.10478097, 0.15179799],
       [0.03651419, 0.02675199, 0.55782126, 0.30608991, 0.07282265]])