# Activation Functions

This workbook contains.

In [9]:
import tensorflow as tf
import numpy as np

In [10]:
import warnings

warnings.filterwarnings('ignore')

## 1. Breakdown of Problem Types, Activation and Loss Functions

| Problem Type    | Output Type                        | Final Activation Function  | Loss Function         |
| ---             | ---                                | ---                        | ---                   |
| Regression      | Numerical                          | Linear                     | Mean Squared Error    |
| Classification  | Binary                             | Sigmoid                    | Binary Cross Entropy  |
| Classification  | Single label, multiple classes     | Softmax                    | Cross Entropy         |
| Classification  | Multiple labels, multiple classes  | Sigmoid                    | Binary Cross Entropy  |

## 2. Softmax vs Log Softmax Activation

In [11]:
test_input = np.random.randn(2, 5)
test_input

array([[ 0.96974612,  0.30680782, -0.51262661,  1.16747533, -0.25232825],
       [ 0.52992512, -0.314935  , -0.24383512,  0.04063838,  0.97421128]])

Softmax returns the probability that each input belongs to a certain class.

In [12]:
softmax_output = tf.nn.softmax(test_input)
softmax_output

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[0.30715513, 0.15828776, 0.06975438, 0.37430918, 0.09049355],
       [0.24610339, 0.10573031, 0.11352141, 0.15087701, 0.38376788]])>

Taking the sum at column level shows that they add up to 1.

In [13]:
np.sum(softmax_output, axis=1)

array([1., 1.])

## 3. Advantages and Disdvantages of Log Softmax

### 3.1 Advantages

- logarithm function is much better at handling extreme values.

In [14]:
log_softmax_output = tf.nn.log_softmax(test_input)
log_softmax_output

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[-1.18040235, -1.84334064, -2.66277507, -0.98267313, -2.40247672],
       [-1.40200355, -2.24686367, -2.17576379, -1.89129029, -0.95771739]])>

In [15]:
np.exp(log_softmax_output)

array([[0.30715513, 0.15828776, 0.06975438, 0.37430918, 0.09049355],
       [0.24610339, 0.10573031, 0.11352141, 0.15087701, 0.38376788]])